version: 2
updates:
  - package-ecosystem: pip
    directory: /apps/assistant-backend
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /apps/assistant-ui
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
